### ISSUE TITLE
evaluation without wandb logging

### ISSUE THREAD

**Issue by leyuan-sun** [allenai/procthor-rl#1]
Is it possible to evaluate pre-trained model without wandb logging?

Another issue when I used the provided pre-trained model to do evaluation:  

` python procthor_objectnav/main.py     experiment=procthor_objectnav/experiments/rgb_clipresnet50gru_ddppo     agent=locobot     target_object_types=robothor_habitat2022     machine.num_train_processes=1     machine.num_test_processes=20     ai2thor.platform=CloudRendering     model.add_prev_actions_embedding=true        seed=100     eval=true     evaluation.tasks=["architector"]     evaluation.minival=false     checkpoint=/home/procthor-rl-main/pretrained_models     visualize=true 
`

An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/hydra/_internal/utils.py", line 252, in run_and_report
    assert mdl is not None
AssertionError

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'procthor_objectnav'

**Comment by KuoHaoZeng** [comment]
Hi! You might want to add `PYTHONPATH=.` before your python command, so that `hydra` could find the `main.yaml`.
In addition, I found there is a typo in the task name: `architector` -> `architecthor`
Note that the evaluation won't record the visualization of trajectories without the wandb logging.

**Comment by leyuan-sun** [comment]
Thanks for your reply, I did evluation without wandb logging. I got the following error:

thor-CloudRendering-ca10d107fb46cb051dba99af484181fda9947a28.zip: [|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                                                                                                                50%   1.3 MiB/s]  of 797.MB[04/24 08:51:44 ERROR:] [test worker 2] Encountered TimeoutError, exiting.       [engine.py: 2355]

procthor-rl/lib/python3.9/site-packages/allenact/algorithms/onpolicy_sync/vector_sampled_tasks.py", line 272, in read_with_timeout
    raise TimeoutError(
TimeoutError: Did not receive output from `VectorSampledTask` worker for 300 seconds.

Also I want to know where the cloudrendering zip file been stored?

**Comment by leyuan-sun** [comment]
I tried to use Linux64 instead of CloudRendering as platform. but got the following error:

[04/24 09:48:36 INFO:] Starting 0-th SingleProcessVectorSampledTasks generator with args {'mp_ctx': <multiprocessing.context.ForkServerContext object at 0x7f64559af640>, 'task_sampler_args': TaskSamplerArgs(process_ind=6, mode='eval', house_inds=[720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839], houses=Dataset(
    dataset=architecthor|object-nav-eval,
    size=1200,
    split=val
), sensors=[<procthor_objectnav.sensors.vision.RGBSensorThorController object at 0x7f64559a4f70>, <allenact_plugins.ithor_plugin.ithor_sensors.GoalObjectTypeThorSensor object at 0x7f64559af2b0>], controller_args={'commit_id': 'ca10d107fb46cb051dba99af484181fda9947a28', 'width': 400, 'height': 300, 'rotateStepDegrees': 30, 'visibilityDistance': 1, 'gridSize': 0.25, 'agentMode': 'locobot', 'fieldOfView': 63.453048374758716, 'snapToGrid': False, 'renderDepthImage': False, 'renderInstanceSegmentation': False, 'x_display': ':0.1'}, reward_config=RewardConfig(step_penalty=-0.01, goal_success_reward=10.0, failed_stop_reward=0.0, shaping_weight=0.0, reached_horizon_reward=0.0, positive_only_reward=False), target_object_types=['AlarmClock', 'Apple', 'BaseballBat', 'BasketBall', 'Bed', 'Bowl', 'Chair', 'GarbageCan', 'HousePlant', 'Laptop', 'Mug', 'Sofa', 'SprayBottle', 'Television', 'Toilet', 'Vase'], max_steps=500, max_tasks=120, distance_type='l2', resample_same_scene_freq=100, p_randomize_materials=0.8, test_on_validation=True, actions=['MoveAhead', 'RotateLeft', 'RotateRight', 'End', 'LookUp', 'LookDown'], max_agent_positions=6, max_vis_points=6, p_greedy_target_object=0.8, ithor_p_shuffle_objects=0, valid_agent_heights=[0.8697997], visualize=False, deterministic_cudnn=False, loop_dataset=True, seed=1873586768, allow_flipping=False)}.  [vector_sampled_tasks.py: 1102]
[04/24 09:48:36 ERROR:] [test worker 2] Encountered BrokenPipeError, exiting.   [engine.py: 2355]
[04/24 09:48:36 ERROR:] Traceback (most recent call last):

**Comment by rginjapan** [comment]
With wandb logging during evaluation, I met the following error:

/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/wandb/util.py", line 873, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access
wandb: ERROR Internal wandb error: file data was not synced

**Comment by leyuan-sun** [comment]
When I used wandb logging for evaluation, during a big file for cloudrendering, there is a following error:

 File "/home/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/allenact/algorithms/onpolicy_sync/vector_sampled_tasks.py", line 237, in <listcomp>
    for space in read_fn(timeout_to_use=5 * self.read_timeout if self.read_timeout is not None else None)  # type: ignore
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/allenact/algorithms/onpolicy_sync/vector_sampled_tasks.py", line 272, in read_with_timeout
    raise TimeoutError(
TimeoutError: Did not receive output from `VectorSampledTask` worker for 300 seconds.
        [engine.py: 2358]
thor-CloudRendering-ca10d107fb46cb051dba99af484181fda9947a28.zip: [|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                                                                                                                                      42%   1.0 MiB/s]  of 797.MB[04/24 11:21:43 ERROR:] Encountered Exception. Terminating runner.       [runner.py: 1467]
[04/24 11:21:43 ERROR:] Traceback (most recent call last):

**Comment by NinjaCXX** [comment]
@rginjapan 
I met the same error with you, have you solved the problem?

**Comment by leyuan-sun** [comment]
I solved by increasing the `timeout_to_use` if I remembered correctly.

**Comment by NinjaCXX** [comment]
> timeout_to_use

Thank you very much.

**Comment by flyflyly** [comment]
> I solved by increasing the `timeout_to_use` if I remembered correctly.

how to do it ?
