### ISSUE TITLE
evaluate on robothor

### ISSUE THREAD

**Issue by leyuan-sun** [allenai/procthor-rl#4]
I can evaluate on architecthor successfully, and I would like to evaluate on robothor dataset by switching:
    evaluation.tasks=["architecthor"]  to robothor and I obtained the following error:

Process ForkServerProcess-4:3:
Traceback (most recent call last):
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/allenact/algorithms/onpolicy_sync/vector_sampled_tasks.py", line 346, in _task_sampling_loop_worker
    sp_vector_sampled_tasks = SingleProcessVectorSampledTasks(
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/allenact/algorithms/onpolicy_sync/vector_sampled_tasks.py", line 897, in __init__
    self._vector_task_generators: List[Generator] = self._create_generators(
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/allenact/algorithms/onpolicy_sync/vector_sampled_tasks.py", line 1116, in _create_generators
    if next(generators[-1]) != "started":
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/allenact/algorithms/onpolicy_sync/vector_sampled_tasks.py", line 962, in _task_sampling_loop_generator_fn
    current_task = task_sampler.next_task()
  File "/home/procthor-rl-main/procthor_objectnav/tasks/object_nav.py", line 759, in next_task
    self.controller = Controller(**self.args.controller_args)
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/ai2thor/controller.py", line 513, in __init__
    self._build = self.find_build(local_build, commit_id, branch, platform)
  File "/home/anaconda3/envs/procthor-rl/lib/python3.9/site-packages/ai2thor/controller.py", line 1306, in find_build
    raise ValueError(
ValueError: Invalid commit_id: bad5bc2b250615cb766ffb45d455c211329af17e - no build exists for arch=Linux platforms=CloudRendering
^C[04/24 15:41:57 INFO:] Interrupt signal sent to worker Test-1. Forcing worker Test-1 to close and exiting.    [runner.py: 353]
[04/24 15:41:57 INFO:] Interrupt signal sent to worker Test-0. Forcing worker Test-0 to close and exiting.      [runner.py: 353]
[04/24 15:41:57 INFO:] KeyboardInterrupt. Terminating runner.   [runner.py: 1465]
[04/24 15:41:57 INFO:] Interrupt signal sent to worker Test-2. Forcing worker Test-2 to close and exiting.      [runner.py: 353]
[04/24 15:41:57 INFO:] Terminating test 0       [runner.py: 1543]
[04/24 15:41:57 INFO:] Terminating test 1       [runner.py: 1543]
[04/24 15:41:57 INFO:] Termination signal sent to worker Test-0. Worker Test-0 is already closed, exiting.      [runner.py: 348]
[04/24 15:41:57 INFO:] Terminating test 2       [runner.py: 1543]
[04/24 15:41:57 INFO:] Termination signal sent to worker Test-1. Worker Test-1 is already closed, exiting.      [runner.py: 348]
[04/24 15:41:57 INFO:] Joining test 0   [runner.py: 1543]
[04/24 15:41:57 INFO:] Termination signal sent to worker Test-2. Worker Test-2 is already closed, exiting.      [runner.py: 348]

**Comment by izilu** [comment]
I came across the same problem. Is there any solution for this? @KuoHaoZeng
